# Generated by Django 3.1.2 on 2020-10-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswer',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionandanswer',
            name='title',
            field=models.CharField(default='write your question title', max_length=100),
        ),
    ]
