# Generated by Django 3.1.2 on 2020-10-30 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNumberDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapNo', models.IntegerField()),
                ('InnerChapOne', models.IntegerField(default=1)),
                ('InnerChapTwo', models.IntegerField(default=2)),
                ('ChapName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationPracticeAnswerDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapNo', models.IntegerField()),
                ('InnerNo', models.IntegerField()),
                ('SentenceNo', models.IntegerField()),
                ('Cosentence_answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationPracticeQuestionDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapNo', models.IntegerField()),
                ('InnerNo', models.IntegerField()),
                ('SentenceNo', models.IntegerField()),
                ('Cosentence_question', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EssentialSentenceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapNo', models.IntegerField()),
                ('InnerNo', models.IntegerField()),
                ('SentenceNo', models.IntegerField()),
                ('Essentence_question', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CheckProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_1', models.IntegerField(default=1)),
                ('chap_2', models.IntegerField(default=1)),
                ('chap_3', models.IntegerField(default=1)),
                ('chap_4', models.IntegerField(default=1)),
                ('chap_5', models.IntegerField(default=1)),
                ('chap_6', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkprocess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
