# Generated by Django 3.1.2 on 2020-11-11 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20201105_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkprocess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_checkprocess', to=settings.AUTH_USER_MODEL),
        ),
    ]
