# Generated by Django 3.1.2 on 2020-11-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201111_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_6',
            field=models.IntegerField(default=0),
        ),
    ]
