# Generated by Django 3.1.2 on 2020-11-11 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_auto_20201111_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckProcessTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapNo', models.IntegerField()),
                ('InnerChapNo', models.IntegerField()),
                ('is_check', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_checktable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
